### ISSUE TITLE
For Android Platform : Update Tts.java file

### ISSUE THREAD

**Issue by prameshkumar** [CognitiveBuild/WatsonSpeechPlugin#2]
Hi ,

i found an issue while taking a build after added a plugin & fixed the issue using below changes !
Please update a speech to text files .

For your reference,

Add two methods in Tts.java file

@Override
    public void onTTSStopped() {
        Log.d(TAG, "### onTTSStopped ###");
    }

    @Override
    public void onTTSError(int statusCode) {
        Log.d(TAG, "### onTTSError: "+statusCode+" ###");
        this.synthesizeContext.error("Synthesize Failed");
    }

 TextToSpeech.sharedInstance().initWithConfig(tConfig,this);

**Comment by mihui** [comment]
Hi @prameshkumar , thanks for reporting this, there are some out-of-date code, and I fixed it. And these two methods are already there in the `Tts.java`: `public void onTTSStopped()` and `public void onTTSError(int statusCode)`, and `TextToSpeech.sharedInstance().initWithConfig(tConfig,this);` is updated in the latest commit.
